<?php

namespace Sample\AddressBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressBookRepository extends EntityRepository
{
}
